### ISSUE TITLE
The result of visemes  is still wrong

### ISSUE THREAD

**Issue by xoyojank** [ChairGraveyard/ovrlipsync-example#1]
no matter what I say, the result seems random.

**Comment by ChairGraveyard** [comment]
I noticed this issue myself and I suspect it might be due to passing the wrong sample rate for the PCM samples provided.

**Comment by xoyojank** [comment]
I have tried 16000, 44100, 48000, all of them are not correct

**Comment by ChairGraveyard** [comment]
22000?

I'm not sure what else it would be, tbh, as I thought I had it set up right.

I'll try and bring in some of the Oculus audio guys to see if they can help.

**Comment by xoyojank** [comment]
I have tested the OVRLipSync without UE4, and found that the OVRLipSyncProcessFrame could not work, only OVRLipSyncProcessFrameInterleaved can generate the right result. But OVRLipSyncProcessFrameInterleaved must be fill with 2 channels of audio data, with the array size twice as   the buffer size seted in OVRLipSyncInit

**Comment by ChairGraveyard** [comment]
Thanks xoyojank, I'll take a look and see if I can't make it work using the interleaved version in UE4. 

Not sure why that would be the case, though, unless the data is stereo, which I was under the impression it wouldn't be.

**Comment by ChairGraveyard** [comment]
Gonna mark this as closed since @xoyojank fixed up the issue and I've since committed the fixed version.
